### ISSUE TITLE
An unbelievable bug in this implementation!

### ISSUE THREAD

**Issue by B1Z0N** [NeverWalkAloner/BreakEnigma#2]
Sorry for such a clickbait naming, I just wanted to grab your attention. I couldn't find your contacts.

You see, right now I'm busy implementing  DSTU4145(regarding cryptographic signature based on elliptic curve cryptography). As I saw on your [page](https://web.archive.org/web/20130705020141/http://web.cryptography.org.ua/ready.html) on web archive, there's an implementation version of your library in 2014 year(v0.01), where you've fixed the problem regarding "Умножение точки на число в ОНБ выполняется с ошибкой для m выше 173. Скорее всего какая-нибудь мелочь. Ее нужно найти. ВЫПОЛНЕНО!!!". Could you please give me a hint on where to find a fix for this issue, or get me in contact with Dmitry Kukushkin.

If you can help, please write to kolausf@gmail.com.

**Comment by NeverWalkAloner** [comment]
Hi, it was long long time ago and I've completely forgotten any details. So the only thing I can do is to share some links. This is the project repo: https://sourceforge.net/p/dstu4145-2002/code/HEAD/tree/
And project author's profile: https://habr.com/ru/users/codecity/
Hope it will be helpful.
